name: Generate PDF

on: 
  push:
  workflow_dispatch:

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - run: mkdir output
      - name: Set date
        run: |
          echo "schvaleno=`.pandoc/getdate.rb`" >> $GITHUB_ENV
      - name: Generate HTML
        uses: docker://pandoc/core:latest
        with:
          args: >-
            --standalone
            --from markdown+ascii_identifiers 
            --metadata title="Stanovy Svobodných"
            -V date="Schváleno ReV dne ${{ env.schvaleno }}"
            --shift-heading-level-by=0
            -V margin-top=15
            -V margin-left=15
            -V margin-right=15
            -V margin-bottom=15
            -V papersize=a4
            --output=output/stanovy.html
            -t html5
            -V default-header
            -A .pandoc/footer.html
            -H .pandoc/header.html
            stanovy.md
      - run: sudo apt-get update 
      - name: Install wkhtmltopdf
        run: |
          sudo apt-get install xvfb libfontconfig wget
          wget https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6.1-2/wkhtmltox_0.12.6.1-2.jammy_amd64.deb
          sudo apt install -f ./wkhtmltox_0.12.6.1-2.jammy_amd64.deb
      - name: Generate PDF
        run: xvfb-run wkhtmltopdf --page-size a4 --title "Stanovy Svobodných" --margin-bottom 35 --margin-top 15 --margin-right 0 --margin-left 0 --enable-local-file-access --header-spacing 12 --header-html .wkhtmltopdf/header.html --footer-spacing 12 --footer-html .wkhtmltopdf/footer.html --replace "schvaleno" "${{ env.schvaleno }}" output/stanovy.html output/stanovy.pdf
      - uses: actions/upload-artifact@master
        with:
          name: Stanovy ${{ env.schvaleno }}
          path: output
